//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epam_FinalProject_FileManager.FileSizeEvaluationServiceNamespace {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileSizeEvaluationServiceNamespace.ISizeEvaluationService")]
    public interface ISizeEvaluationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISizeEvaluationService/Evaluate", ReplyAction="http://tempuri.org/ISizeEvaluationService/EvaluateResponse")]
        string Evaluate(long bytes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISizeEvaluationService/Evaluate", ReplyAction="http://tempuri.org/ISizeEvaluationService/EvaluateResponse")]
        System.Threading.Tasks.Task<string> EvaluateAsync(long bytes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISizeEvaluationServiceChannel : Epam_FinalProject_FileManager.FileSizeEvaluationServiceNamespace.ISizeEvaluationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SizeEvaluationServiceClient : System.ServiceModel.ClientBase<Epam_FinalProject_FileManager.FileSizeEvaluationServiceNamespace.ISizeEvaluationService>, Epam_FinalProject_FileManager.FileSizeEvaluationServiceNamespace.ISizeEvaluationService {
        
        public SizeEvaluationServiceClient() {
        }
        
        public SizeEvaluationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SizeEvaluationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SizeEvaluationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SizeEvaluationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Evaluate(long bytes) {
            return base.Channel.Evaluate(bytes);
        }
        
        public System.Threading.Tasks.Task<string> EvaluateAsync(long bytes) {
            return base.Channel.EvaluateAsync(bytes);
        }
    }
}
